### ISSUE TITLE
Ceramic fails to start up if there are documents in the local pinset but the corresponding IPFS data is unavailable

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1019]
```
ceramic daemon --anchor-service-api=http://localhost:8081 --ethereum-rpc=http://localhost:7545 --network=local
Swarm listening on /ip4/127.0.0.1/tcp/4011/p2p/QmTA774XfWej8qBciVMuFyaADhFkLFEyBMDZAxBxsGzTH2
Swarm listening on /ip4/10.0.0.150/tcp/4011/p2p/QmTA774XfWej8qBciVMuFyaADhFkLFEyBMDZAxBxsGzTH2
Swarm listening on /ip4/127.0.0.1/tcp/4012/ws/p2p/QmTA774XfWej8qBciVMuFyaADhFkLFEyBMDZAxBxsGzTH2
Swarm listening on /ip4/10.0.0.150/tcp/4012/ws/p2p/QmTA774XfWej8qBciVMuFyaADhFkLFEyBMDZAxBxsGzTH2
IPFS API server listening on 5011
IPFS Gateway server listening on 9011
Starting Ceramic node at version 0.19.7 with config: 
{
  "logLevel": "silent",
  "gateway": false,
  "networkName": "local",
  "ethereumRpcUrl": "http://localhost:7545",
  "anchorServiceUrl": "http://localhost:8081"
}
Connecting to ceramic network 'local' using pubsub topic '/ceramic/local-3198720619' with supported anchor chains ['eip155:1337']
Peer discovery is not supported for ceramic network local. This node may fail to load documents from other nodes on the network
(node:994178) UnhandledPromiseRejectionWarning: TimeoutError: request timed out
    at maybeThrowTimeoutError (/home/spencer/js-ceramic1/node_modules/ipfs-core/node_modules/ipfs-core-utils/src/with-timeout-option.js:42:15)
    at /home/spencer/js-ceramic1/node_modules/ipfs-core/node_modules/ipfs-core-utils/src/with-timeout-option.js:96:9
(node:994178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:994178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
^ daemon then hangs forever and never starts accepting http connections.  We should catch timeout errors when loading docs from IPFS during document recovery at startup, log a clear warning, and continue with the startup process.

**Comment by stbrody** [comment]
@oed, not sure exactly where to put bug fixes like these that don't belong to any specific project so that they can still be considered in planning.

FYI @ukstv

**Comment by oed** [comment]
@stbrody Just make sure to tag them with the appropriate labels!

**Comment by ukstv** [comment]
Now it starts all right.
