### ISSUE TITLE
Error when validating anchor commits

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1116]
```
TypeError: Cannot read property 'timestamp' of null
    at EthereumAnchorService.validateChainInclusion (/home/spencer/js-ceramic4/packages/core/lib/anchor/ethereum/ethereum-anchor-service.js:144:50)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async verifyAnchorCommit (/home/spencer/js-ceramic4/packages/core/lib/conflict-resolution.js:31:5)
    at async ConflictResolution.applyLogToState (/home/spencer/js-ceramic4/packages/core/lib/conflict-resolution.js:145:17)
    at async Document._handleTip (/home/spencer/js-ceramic4/packages/core/lib/document.js:108:22)
    at async /home/spencer/js-ceramic4/packages/core/lib/document.js:142:29
    at async run (/home/spencer/js-ceramic4/node_modules/p-queue/dist/index.js:163:29)
TypeError: Cannot read property 'blockHash' of null
    at EthereumAnchorService.validateChainInclusion (/home/spencer/js-ceramic4/packages/core/lib/anchor/ethereum/ethereum-anchor-service.js:135:59)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async verifyAnchorCommit (/home/spencer/js-ceramic4/packages/core/lib/conflict-resolution.js:31:5)
    at async ConflictResolution.applyLogToState (/home/spencer/js-ceramic4/packages/core/lib/conflict-resolution.js:145:17)
    at async Document._handleTip (/home/spencer/js-ceramic4/packages/core/lib/document.js:108:22)
    at async /home/spencer/js-ceramic4/packages/core/lib/document.js:142:29
    at async run (/home/spencer/js-ceramic4/node_modules/p-queue/dist/index.js:163:29)
```

**Comment by stbrody** [comment]
We've had reports from the field that this is causes nodes to crash.  It also looks like this may be causing node crashes in our integration tests.  Bumping up the priority

**Comment by stbrody** [comment]
The problem seems to be, as best as I can tell, that sometimes when fetching the transaction or block data from ethereum, we get back either a null [transaction here](https://github.com/ceramicnetwork/js-ceramic/blob/f417e27ce34b56ed43a713ca6697c9f34b1b7ae7/packages/core/src/anchor/ethereum/ethereum-anchor-service.ts#L222) or a null [block here](https://github.com/ceramicnetwork/js-ceramic/blob/f417e27ce34b56ed43a713ca6697c9f34b1b7ae7/packages/core/src/anchor/ethereum/ethereum-anchor-service.ts#L223).
This seems to happen sporadically, and I've even seen it happen after successfully loading the same information for the same transaction (for a different document's anchorcommit that was anchored in the same batch).

In my testing this doesn't crash the node, and if you leave it running long enough it keeps retrying and eventually one of the retries succeeds.  No idea though why the ethers library would sporadically be unable to return information about a transaction that has definitely been mined successfully.

**Comment by stbrody** [comment]
I reverted the `ethers` package to an older version (5.0.18, which we were on for a long time) and still repro the issue.  So my best guess is it's a problem with infura?  No idea why this just started happening recently, but this does seem like a pretty serious issue

**Comment by stbrody** [comment]
I tried setting an `--ethereum-rpc` pointing to an infura endpoint and the errors went away.  So it seems like this is some kind of rate limiting from Infura, just with extremely poor UX and error reporting.  The workaround is just to always start your ceramic nodes with a valid `ethereum-rpc`

**Comment by stbrody** [comment]
Not a bug in Ceramic.  Need to set `--ethereum-rpc` to reliably verify anchor commits
