### ISSUE TITLE
Peer ID mismatch errors on Clay

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1339]
```
>  ceramic daemon
Swarm listening on /ip4/127.0.0.1/tcp/4011/p2p/QmbHeXWFUcYKjM8LPcGsUq87YsQopSq4YM6znietqQ6wkW
Swarm listening on /ip4/10.0.0.150/tcp/4011/p2p/QmbHeXWFUcYKjM8LPcGsUq87YsQopSq4YM6znietqQ6wkW
Swarm listening on /ip4/127.0.0.1/tcp/4012/ws/p2p/QmbHeXWFUcYKjM8LPcGsUq87YsQopSq4YM6znietqQ6wkW
Swarm listening on /ip4/10.0.0.150/tcp/4012/ws/p2p/QmbHeXWFUcYKjM8LPcGsUq87YsQopSq4YM6znietqQ6wkW
IPFS API server listening on 5011
IPFS Gateway server listening on 9011
Starting Ceramic node at version 1.0.0-rc.11 with config:
{
  "gateway": false,
  "networkName": "testnet-clay",
  "loggerConfig": {
    "logLevel": 2,
    "logToFiles": false
  }
}
Connecting to ceramic network 'testnet-clay' using pubsub topic '/ceramic/testnet-clay' and connecting to anchor service 'https://cas-clay.3boxlabs.com' with supported anchor chains ['eip155:3']
Connecting to peers found in 'https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/testnet-clay.json'
Can not connect to /dns4/ipfs-clay-internal.3boxlabs.com/tcp/4012/wss/p2p/QmQotCKxiMWt935TyCBFTN23jaivxwrZ3uD58wNxeg5npi
AggregateError:
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/home/spencer/js-ceramic1/node_modules/libp2p-noise/dist/src/noise.js:166:19)
        at async Noise.performHandshake (/home/spencer/js-ceramic1/node_modules/libp2p-noise/dist/src/noise.js:135:20)
        at async Noise.secureOutbound (/home/spencer/js-ceramic1/node_modules/libp2p-noise/dist/src/noise.js:60:27)
        at async Upgrader._encryptOutbound (/home/spencer/js-ceramic1/node_modules/libp2p/src/upgrader.js:394:12)
        at async Upgrader.upgradeOutbound (/home/spencer/js-ceramic1/node_modules/libp2p/src/upgrader.js:167:11)
        at async ClassIsWrapper.dial (/home/spencer/js-ceramic1/node_modules/libp2p-websockets/src/index.js:54:18)
        at async TransportManager.dial (/home/spencer/js-ceramic1/node_modules/libp2p/src/transport-manager.js:111:14)
        at async /home/spencer/js-ceramic1/node_modules/libp2p/src/dialer/dial-request.js:70:18
        at async /home/spencer/js-ceramic1/node_modules/p-some/index.js:53:19
    at maybeSettle (/home/spencer/js-ceramic1/node_modules/p-some/index.js:31:11)
    at /home/spencer/js-ceramic1/node_modules/p-some/index.js:69:23
Can not connect to /dns4/ipfs-clay-internal.3boxlabs.com/tcp/4012/wss/p2p/QmQotCKxiMWt935TyCBFTN23jaivxwrZ3uD58wNxeg5npi
AggregateError:
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/home/spencer/js-ceramic1/node_modules/libp2p-noise/dist/src/noise.js:166:19)
        at async Noise.performHandshake (/home/spencer/js-ceramic1/node_modules/libp2p-noise/dist/src/noise.js:135:20)
        at async Noise.secureOutbound (/home/spencer/js-ceramic1/node_modules/libp2p-noise/dist/src/noise.js:60:27)
        at async Upgrader._encryptOutbound (/home/spencer/js-ceramic1/node_modules/libp2p/src/upgrader.js:394:12)
        at async Upgrader.upgradeOutbound (/home/spencer/js-ceramic1/node_modules/libp2p/src/upgrader.js:167:11)
        at async ClassIsWrapper.dial (/home/spencer/js-ceramic1/node_modules/libp2p-websockets/src/index.js:54:18)
        at async TransportManager.dial (/home/spencer/js-ceramic1/node_modules/libp2p/src/transport-manager.js:111:14)
        at async /home/spencer/js-ceramic1/node_modules/libp2p/src/dialer/dial-request.js:70:18
        at async /home/spencer/js-ceramic1/node_modules/p-some/index.js:53:19
    at maybeSettle (/home/spencer/js-ceramic1/node_modules/p-some/index.js:31:11)
    at /home/spencer/js-ceramic1/node_modules/p-some/index.js:69:23
Connected to peers: /dns4/ipfs-clay.3boxlabs.com/tcp/4012/wss/p2p/QmWiY3CbNawZjWnHXx3p3DXsg21pZYTj4CRY1iwMkhP8r3, /dns4/ipfs-clay.ceramic.network/tcp/4012/wss/p2p/QmSqeKpCYW89XrHHxtEQEWXmznp6o336jzwvdodbrGeLTk, /dns4/ipfs-clay-cas.3boxlabs.com/tcp/4012/wss/p2p/QmbeBTzSccH8xYottaYeyVX8QsKyox1ExfRx7T1iBqRyCd, /dns4/ipfs-clay-1.ceramic.geoweb.network/tcp/4012/ws/p2p/QmbDGaByZoomn3NQQjZzwaPWH6ei3ptzWK7a7ECtS35DKL
Ceramic API running on 0.0.0.0:7007'
```

**Comment by valmack** [comment]
This should be resolved now. Made some updates and just tested locally and not seeing these errors.

**Comment by chenweisomebody126** [comment]
@v-stickykeys I ran into the same issue
```
$ ceramic daemon
Swarm listening on /ip4/127.0.0.1/tcp/4011/p2p/QmPNJ2bAHeY38NtX8kt3fMu6y5PPSb6hbAbKXp4n7ayZpZ
Swarm listening on /ip4/192.168.1.203/tcp/4011/p2p/QmPNJ2bAHeY38NtX8kt3fMu6y5PPSb6hbAbKXp4n7ayZpZ
Swarm listening on /ip4/127.0.0.1/tcp/4012/ws/p2p/QmPNJ2bAHeY38NtX8kt3fMu6y5PPSb6hbAbKXp4n7ayZpZ
Swarm listening on /ip4/192.168.1.203/tcp/4012/ws/p2p/QmPNJ2bAHeY38NtX8kt3fMu6y5PPSb6hbAbKXp4n7ayZpZ
IPFS API server listening on 5011
IPFS Gateway server listening on 9011
Starting Ceramic Daemon at version 1.10.1 with config: 
{
  "anchor": {},
  "http-api": {
    "cors-allowed-origins": [
      ".*"
    ]
  },
  "ipfs": {
    "mode": "bundled"
  },
  "logger": {
    "log-level": 2,
    "log-to-files": false
  },
  "network": {
    "name": "testnet-clay"
  },
  "node": {},
  "state-store": {
    "mode": "fs",
    "local-directory": "/Users/wei.chen/.ceramic/statestore"
  }
}
Connecting to ceramic network 'testnet-clay' using pubsub topic '/ceramic/testnet-clay'
Connecting to peers found in 'https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/testnet-clay.json'
This node with peerId QmPNJ2bAHeY38NtX8kt3fMu6y5PPSb6hbAbKXp4n7ayZpZ is not included in the peer list for Ceramic network testnet-clay. It will not be discoverable by other nodes in the network, and so data created against this node will not be available to the rest of the network.
Can not connect to /dns4/ipfs-cas-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmbeBTzSccH8xYottaYeyVX8QsKyox1ExfRx7T1iBqRyCd
AggregateError: 
    Error: getaddrinfo ENOTFOUND ipfs-cas-clay-external.3boxlabs.com
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26)
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-noise/dist/src/noise.js:186:19)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Noise.performHandshake (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-noise/dist/src/noise.js:155:20)
        at async Noise.secureOutbound (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-noise/dist/src/noise.js:80:27)
        at async Upgrader._encryptOutbound (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/upgrader.js:406:12)
        at async Upgrader.upgradeOutbound (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/upgrader.js:176:11)
        at async ClassIsWrapper.dial (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-websockets/src/index.js:54:18)
        at async TransportManager.dial (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/transport-manager.js:111:14)
        at async /usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/dialer/dial-request.js:71:18
        at async /usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/p-some/index.js:53:19
    at maybeSettle (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/p-some/index.js:31:11)
    at /usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/p-some/index.js:69:23
Can not connect to /dns4/ipfs-ceramic-private-cas-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmbeBTzSccH8xYottaYeyVX8QsKyox1ExfRx7T1iBqRyCd
AggregateError: 
    Error: getaddrinfo ENOTFOUND ipfs-cas-clay-external.3boxlabs.com
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26)
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-noise/dist/src/noise.js:186:19)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Noise.performHandshake (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-noise/dist/src/noise.js:155:20)
        at async Noise.secureOutbound (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-noise/dist/src/noise.js:80:27)
        at async Upgrader._encryptOutbound (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/upgrader.js:406:12)
        at async Upgrader.upgradeOutbound (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/upgrader.js:176:11)
        at async ClassIsWrapper.dial (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p-websockets/src/index.js:54:18)
        at async TransportManager.dial (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/transport-manager.js:111:14)
        at async /usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/libp2p/src/dialer/dial-request.js:71:18
        at async /usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/p-some/index.js:53:19
    at maybeSettle (/usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/p-some/index.js:31:11)
    at /usr/local/lib/node_modules/@ceramicnetwork/cli/node_modules/p-some/index.js:69:23
Connected to peers: /dns4/ipfs-ceramic-public-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmWiY3CbNawZjWnHXx3p3DXsg21pZYTj4CRY1iwMkhP8r3, /dns4/ipfs-ceramic-public-clay-external.ceramic.network/tcp/4012/wss/p2p/QmSqeKpCYW89XrHHxtEQEWXmznp6o336jzwvdodbrGeLTk, /dns4/ipfs-ceramic-private-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmQotCKxiMWt935TyCBFTN23jaivxwrZ3uD58wNxeg5npi, /ip4/165.232.129.204/tcp/4012/ws/p2p/QmbDGaByZoomn3NQQjZzwaPWH6ei3ptzWK7a7ECtS35DKL
Connected to anchor service 'https://cas-clay.3boxlabs.com' with supported anchor chains ['eip155:3']
Ceramic API running on 0.0.0.0:7007'
```
And when I ran 
```
$ ceramic create tile --content '{ "Foo": "Bar" }'
request to http://localhost:7007/api/v0/streams failed, reason: connect ECONNREFUSED ::1:7007
```
