### ISSUE TITLE
Can not install 1.0.5 - missing dep ipfs-repo

### ISSUE THREAD

**Issue by v-stickykeys** [ceramicnetwork/js-ceramic#1466]
Someone reported this in Discord and I was able to repro on a clean install

```
npm install -g @ceramicnetwork/cli
```

```
~|⇒ ceramic daemon
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'ipfs-core'
Require stack:
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/index.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/build-ipfs-connection.util.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-cli-utils.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/bin/ceramic.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js:7:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/index.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/build-ipfs-connection.util.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-cli-utils.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/bin/ceramic.js'
  ]
}
```

**Comment by oed** [comment]
Looks like ipfs was removed here: https://github.com/ceramicnetwork/js-ceramic/commit/c9438bdecf0238016314565e0fc86b39097c833d#diff-bae762986b0a4bd16020478571d0eb86852ee763cb8e1d250f6a6d6623a18133L41

**Comment by oed** [comment]
Should be fixed by https://github.com/ceramicnetwork/js-ceramic/pull/1465
