### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by pvanroos** [ceramicnetwork/js-ceramic#1556]
**Describe the bug**
After executing 'ceramic daemon' and observing that the ceramic daemon successfully starts, process will crash after running for a few minutes.

Console log output right after crash:

node:events:353
      throw er; // Unhandled 'error' event
      ^

TypeError: cb is not a function
    at C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\index.js:336:7
    at C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\lib\upnp\device.js:61:11
    at Parser.<anonymous> (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\node_modules\xml2js\lib\parser.js:304:18)
    at Parser.emit (node:events:376:20)
    at Parser.EventEmitter.emit (node:domain:470:12)
    at SAXParser.onclosetag (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\node_modules\xml2js\lib\parser.js:262:26)
    at emit (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\sax\lib\sax.js:640:35)
    at emitNode (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\sax\lib\sax.js:645:5)
    at closeTag (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\sax\lib\sax.js:905:7)
    at SAXParser.write (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\sax\lib\sax.js:1449:13)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\node_modules\xml2js\lib\parser.js:327:16)
    at Parser.parseString (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\node_modules\xml2js\lib\parser.js:5:59)
    at Request._callback (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\@motrix\nat-api\lib\upnp\device.js:53:16)
    at Request.self.callback (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\request\request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.EventEmitter.emit (node:domain:470:12)
    at Request.<anonymous> (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:376:20)
    at Request.EventEmitter.emit (node:domain:470:12)
    at IncomingMessage.<anonymous> (C:\Users\pvanroos\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\request\request.js:1076:12)

**To Reproduce**
1. Obtain a Windows 10 Enterprise machine (non-VM) (10.0.19042 Build 19042)
2. Start 'cmd' window
3. Install npm (v6.14.0) and node (v15.4.0)
4. npm install -g @ceramicnetwork/cli@1.1.0 (idx and idx cli installed along side at global level)
5. start daemon and wait ('ceramic daemon' - no flags added to start)

**Expected behavior**
Stay connected to ceramic decentralized network.

**Screenshots**

**Ceramic versions** 
@ceramicnetwork/cli@1.1.0

**Machine, OS, browser information (please complete the following information):**
Windows 10 Enterprise machine (non-VM) (10.0.19042 Build 19042)

**Additional context**

**Comment by oed** [comment]
Hey @pvanroos thanks for reporting!

Are you running any commands against the daemon or are you just letting it run without touching it?

**Comment by stbrody** [comment]
Also, what happens if you use Node v14?  Ceramic has only been tested on Node v14

**Comment by pvanroos** [comment]
@oed Just running it without touching it.  It starts fine.  I'm looking at the log output and trying to determine if I can share here without redacting anything.  Oh screw it, I'll share it:

> C:\Users\[username]>ceramic daemon
Swarm listening on /ip4/172.31.192.1/tcp/4011/p2p/QmYzuaf2TDvyF3mmTTQwDv5jkDSwg64gvrJBTQVgbFcNU6
Swarm listening on /ip4/192.168.1.42/tcp/4011/p2p/QmYzuaf2TDvyF3mmTTQwDv5jkDSwg64gvrJBTQVgbFcNU6
Swarm listening on /ip4/127.0.0.1/tcp/4011/p2p/QmYzuaf2TDvyF3mmTTQwDv5jkDSwg64gvrJBTQVgbFcNU6
Swarm listening on /ip4/172.31.192.1/tcp/4012/ws/p2p/QmYzuaf2TDvyF3mmTTQwDv5jkDSwg64gvrJBTQVgbFcNU6
Swarm listening on /ip4/192.168.1.42/tcp/4012/ws/p2p/QmYzuaf2TDvyF3mmTTQwDv5jkDSwg64gvrJBTQVgbFcNU6
Swarm listening on /ip4/127.0.0.1/tcp/4012/ws/p2p/QmYzuaf2TDvyF3mmTTQwDv5jkDSwg64gvrJBTQVgbFcNU6
IPFS API server listening on 5011
IPFS Gateway server listening on 9011
Starting Ceramic node at version 1.2.0 with config:
{
  "gateway": false,
  "networkName": "testnet-clay",
  "loggerConfig": {
    "logLevel": 2,
    "logToFiles": false
  }
}
Connecting to ceramic network 'testnet-clay' using pubsub topic '/ceramic/testnet-clay'
Connecting to peers found in 'https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/testnet-clay.json'
Connected to peers: /dns4/ipfs-cas-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmbeBTzSccH8xYottaYeyVX8QsKyox1ExfRx7T1iBqRyCd, /ip4/165.232.129.204/tcp/4012/ws/p2p/QmbDGaByZoomn3NQQjZzwaPWH6ei3ptzWK7a7ECtS35DKL, /dns4/ipfs-ceramic-public-clay-external.ceramic.network/tcp/4012/wss/p2p/QmSqeKpCYW89XrHHxtEQEWXmznp6o336jzwvdodbrGeLTk, /dns4/ipfs-ceramic-public-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmWiY3CbNawZjWnHXx3p3DXsg21pZYTj4CRY1iwMkhP8r3, /dns4/ipfs-ceramic-private-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmQotCKxiMWt935TyCBFTN23jaivxwrZ3uD58wNxeg5npi
Connected to anchor service 'https://cas-clay.3boxlabs.com' with supported anchor chains ['eip155:3']
Ceramic API running on 0.0.0.0:7007'

**Comment by pvanroos** [comment]
@stbrody I can downgrade to Node v14 and see what happens. I'll report back.
