### ISSUE TITLE
Error: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by lyd0** [ceramicnetwork/js-ceramic#1696]
**Describe the bug**
We found this bug when we connected the ceramic daemon to the out-of-process ipfs daemon (when we just started the ceramic daemon)

**To Reproduce**
1. Start the ipfs server (ipfs-daemon)
2. Start the ceramic server (ceramic daemon --network elp --ipfs-api myIpfsHostUrl)

**Ceramic versions** 
1.3.0

**Machine, OS, browser information (please complete the following information):**
ubuntu

**Additional context**
This error appears on the console on the ipfs server: 
(node:27613) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding
    at ServerResponse._storeHeader (_http_outgoing.js:476:11)
    at ServerResponse.writeHead (_http_server.js:332:8)
    at Object.internals.writeHead (/home/ec2-user/.nvm/versions/node/v14.17.4/lib/node_modules/@ceramicnetwork/cli/node_modules/@hapi/hapi/lib/transmit.js:351:13)
    at Object.internals.transmit (/home/ec2-user/.nvm/versions/node/v14.17.4/lib/node_modules/@ceramicnetwork/cli/node_modules/@hapi/hapi/lib/transmit.js:106:15)
    at Object.internals.fail (/home/ec2-user/.nvm/versions/node/v14.17.4/lib/node_modules/@ceramicnetwork/cli/node_modules/@hapi/hapi/lib/transmit.js:70:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Request._reply (/home/ec2-user/.nvm/versions/node/v14.17.4/lib/node_modules/@ceramicnetwork/cli/node_modules/@hapi/hapi/lib/request.js:458:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27613) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27613) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lyd0** [comment]
This error appears on the console on the ipfs server

**Comment by v-stickykeys** [comment]
@lyd0 Can you provide more details here? I am yet to see this warning about trailers.

In particular can you share the architecture?
- Are you trying to connect through load balancer or proxy server?
- Do ipfs and ceramic run on the same machine?

Can you share the ipfs api endpoint being passed?

Is it the IPFS node having a problem or the Ceramic node?
Is it failing to start or is it just showing these warnings?
