### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1801]
* canary-integration/src/__tests__/caip10/near.test.ts: https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/4453/workflows/06f74cbe-7fcd-498f-a9af-2d54b05ab341/jobs/4718

```
 FAIL  src/__tests__/caip10/near.test.ts
  ● Test suite failed to run

    Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.

      at mapper (../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)
```

======================================================================================

* canary-integration/src/__tests__/caip10/polkadot.test.ts: https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/4548/workflows/b9917286-42e1-4f0d-92f1-1dc778ae7070/jobs/4815
```
 FAIL  src/__tests__/caip10/polkadot.test.ts (21.805 s)
  ● happy path

    Invalid proof for signed commit

       97 |     }
       98 |     if (!validProof) {
    >  99 |       throw new Error('Invalid proof for signed commit')
          |             ^
      100 |     }
      101 |
      102 |     if (

      at Caip10LinkHandler._applySigned (../stream-caip10-link-handler/src/caip10-link-handler.ts:99:13)
      at ConflictResolution.applyCommitDataToState (../core/src/conflict-resolution.ts:260:24)
      at ConflictResolution.applyLogToState (../core/src/conflict-resolution.ts:292:17)
      at StateManager._handleTip (../core/src/state-management/state-manager.ts:174:18)
      at ../core/src/state-management/state-manager.ts:228:7
      at run (../../node_modules/p-queue/dist/index.js:163:29)
```

======================================================================================

* cli/src/__tests__/ceramic-error.test.ts: https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/4453/workflows/412c2f92-ade9-46d8-9ae1-3b63c3a27e18/jobs/4714
```
 FAIL  src/__tests__/ceramic-error.test.ts
  ● Test suite failed to run

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)
```

======================================================================================

* blockchain-utils-validation/src/blockchains/__tests__/polkadot.test.ts: https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/4449/workflows/ec6fc085-db37-4454-beae-db24912b5ba6/jobs/4710

```
 FAIL  src/blockchains/__tests__/polkadot.test.ts
  ● Blockchain: Polkadot › validateLink › validate proof with secp256k

    expect(received).resolves.toEqual(expected) // deep equality

    Expected: {"account": "5GuAnwx9uKSQxKZB8moxoaX4ceehoCYu4XYMjJkKtm2QDgqC@polkadot:b0a8d493285c2df73290dfb7e61f870f", "message": "Link this account to your identity·
    did:3:bafysdfwefwe·
    Timestamp: 1635800527", "signature": "0x02a380b64c6fe8423b35653cb8f64457e0779d6084cbc38977153e3c2c2181fef775dbf7eef5a37c45ea9eccb3d8190df5b6fc430b8aaba96767b36870dd6b5801", "timestamp": 1635800527, "type": "eoa", "version": 2}
    Received: null

      71 |       )
      72 |       const proof = await authProvider.createLink(did)
    > 73 |       await expect(polkadot.validateLink(proof)).resolves.toEqual(proof)
         |                                                           ^
      74 |     })
      75 |   })
      76 |

      at Object.toEqual (../../node_modules/expect/build/index.js:198:20)
      at Object.<anonymous> (src/blockchains/__tests__/polkadot.test.ts:73:59)
```

======================================================================================

* All tests pass, but then suite never exits and eventually times out: https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/4548/workflows/50e37fde-14c3-42b5-800e-369075b3493d/jobs/4817
```
Test Suites: 8 passed, 8 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        187.421 s
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

Too long with no output (exceeded 30m0s): context deadline exceeded
```

**Comment by stbrody** [comment]
@glcohen @oed
Not sure how to triage this.  This is the kind of thing that never feels highest priority, but has a constant low-level amount of time suck every time someone needs to look into why their test run failed only to see it's one of these ongoing sporadic failures.

**Comment by stbrody** [comment]
FYI @smrz2001 @ukstv @stephhuynh18 - if you are aware of other tests that you have seen fail multiple times, but pass most of the time, please add them here.
