### ISSUE TITLE
Dispatcher not decoding messages properly

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#339]
From debugging it seems this line is causing the error below. See: https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/ceramic-core/src/dispatcher.ts#L103

` const { typ, id, cid } = JSON.parse(message.data)`

```
(node:79781) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token , in JSON at position 3
    at JSON.parse (<anonymous>)
    at Dispatcher.<anonymous> (/Users/val/Code/js-ceramic/packages/ceramic-core/lib/dispatcher.js:96:47)
    at Generator.next (<anonymous>)
    at /Users/val/Code/js-ceramic/packages/ceramic-core/lib/dispatcher.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/val/Code/js-ceramic/packages/ceramic-core/lib/dispatcher.js:4:12)
    at Dispatcher.handleMessage (/Users/val/Code/js-ceramic/packages/ceramic-core/lib/dispatcher.js:89:16)
    at readMessages (/Users/val/Code/js-ceramic/node_modules/ipfs-http-client/src/pubsub/subscribe.js:77:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Actual
The message data is received as a buffer `"data":{"0":123,"1":34,"2":116,"3":121,"4":112,"5":34,"6":58,"7":48,"8":44,...`

### Expected
It should be json
```json
{
"typ":0,
"id":"/ceramic/bagcqcera74id723qaqdcrfoigb35juhwjxra4yibx65q5fvcsl7myay4ypnq",
"cid":"bagcqcera4khvqsrclxifb2n5yikt7grh6pldek7cxx4sjbcgxsdpurrrmwtq",
"doctype":"tile"
}
```

**Comment by valmack** [comment]
Looks like this may be fixed but not sure where. No longer seeing the issue

**Comment by valmack** [comment]
I have a patch in this in #352  but will leave it open because we need a better way of handling it
