### ISSUE TITLE
Ceramic daemon memory leaks and eventually stops responding to requests

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#483]
I've been using the ceramic-cli to run a daemon. Occasionally I see warnings from the anchor service:

```
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmPWBdXZQaMgbsCLqR5P84xzdPH3JDWyeVPcEWYemVXW5B
Swarm listening on /ip4/192.168.1.3/tcp/4002/p2p/QmPWBdXZQaMgbsCLqR5P84xzdPH3JDWyeVPcEWYemVXW5B
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmPWBdXZQaMgbsCLqR5P84xzdPH3JDWyeVPcEWYemVXW5B
Ceramic API running on port 7007
(node:84785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 kjzl6cwe1jw148qkt1jchpbslkcqv29s84tol98k7698968z5zh6d74wirgbclu listeners added to [EthereumAnchorService]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:84785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 kjzl6cwe1jw149mjcu2a8xo5drpywl9rp4yffyx0oq8wdxjwlcgmdw2prngxcx0 listeners added to [EthereumAnchorService]. Use emitter.setMaxListeners() to increase limit
(node:84785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 kjzl6cwe1jw149mjcu2a8xo5drpywl9rp4yffyx0oq8wdxjwlcgmdw2prngxcx0 listeners added to [EthereumAnchorService]. Use emitter.setMaxListeners() to increase limit
```

I'm not sure if these two things are correlated yet, but eventually the Daemon seems to stop responding, even when the process is still running. My app throws error messages:

```
(node:89494) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:7007/api/v0/state/ceramic/k2t6wyfsu4pg179szhoj03vhlag6cpk66lutm1lffdchkruo2zaen0u4clj9hx failed, reason: connect EADDRNOTAVAIL 127.0.0.1:7007 - Local (0.0.0.0:0)
```

Restarting the daemon fixes the issue

**Comment by simonovic86** [comment]
@Schwartz10 hm, interesting. There might be two separate issues. I'll take a look, tnx!

**Comment by Schwartz10** [comment]
Sure, this is actually becoming quite a problem - seems the daemon almost always crashes.

Here are some logs, and a script, that cause us a problem:

```
> ceramic daemon

Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmPWBdXZQaMgbsCLqR5P84xzdPH3JDWyeVPcEWYemVXW5B
Swarm listening on /ip4/192.168.1.3/tcp/4002/p2p/QmPWBdXZQaMgbsCLqR5P84xzdPH3JDWyeVPcEWYemVXW5B
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmPWBdXZQaMgbsCLqR5P84xzdPH3JDWyeVPcEWYemVXW5B
Ceramic API running on port 7007
(node:8674) UnhandledPromiseRejectionWarning: Error: stream reset
    at Object.reset (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/stream.js:72:27)
    at Mplex._handleIncoming (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:227:16)
    at /Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:156:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Mplex.sink (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:149:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6907)
(node:8674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) UnhandledPromiseRejectionWarning: Error: stream reset
    at Object.reset (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/stream.js:72:27)
    at Mplex._handleIncoming (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:227:16)
    at /Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:156:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Mplex.sink (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:149:9)
(node:8674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12751)
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) UnhandledPromiseRejectionWarning: Error: stream reset
    at Object.reset (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/stream.js:72:27)
    at Mplex._handleIncoming (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:227:16)
    at /Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:156:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Mplex.sink (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:149:9)
(node:8674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14688)
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:8674) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

```js
import fs from "fs";
import Ceramic from "@ceramicnetwork/ceramic-http-client";
import IdentityWallet from "identity-wallet";
import {
  createDefinition,
  publishIDXConfig,
  publishSchema,
} from "@ceramicstudio/idx-tools";
import { DefinitionsAliases } from "@ceramicstudio/idx";
import { fullSchemaList } from "../schemas";
import { getBasicAuth } from "../src/utils";

const auth = getBasicAuth("squad@infinitescroll.org");

const publishSchemas = async (
  ceramic: Ceramic
): Promise<DefinitionsAliases> => {
  const schemas = await Promise.all(
    fullSchemaList.map(async (schema) => {
      const docID = await publishSchema(ceramic, schema);
      return { name: schema.name, docID: docID.toUrl("base36") };
    })
  );
  const schemaMap = {} as { [key: string]: string };
  schemas.forEach((s) => {
    schemaMap[s.name] = s.docID.toString();
  });

  return schemaMap;
};

const publishDefinitions = async (
  ceramic: Ceramic,
  schemas: DefinitionsAliases
): Promise<DefinitionsAliases> => {
  const definitions = {} as DefinitionsAliases;
  for (const k in schemas) {
    const docID = await createDefinition(ceramic, {
      name: k,
      schema: schemas[k],
    });
    definitions[k] = docID.toString();
  }
  return definitions;
};

const seedDefinitions = async () => {
  const ceramic = new Ceramic();
  const idWallet = await IdentityWallet.create({
    authId: auth.ID,
    authSecret: auth.secret,
    getPermission: () => Promise.resolve([]),
    ceramic,
  });
  await ceramic.setDIDProvider(idWallet.getDidProvider());
  console.log("set the prov");
  await publishIDXConfig(ceramic);
  console.log("config published");
  const schemas = await publishSchemas(ceramic);
  console.log("schemas", schemas);
  const definitions = await publishDefinitions(ceramic, schemas);
  fs.writeFile(
    `${__dirname}/../definitions.json`,
    JSON.stringify(definitions),
    console.error
  );

  ceramic.close();
};

seedDefinitions();
```

Eventually the daemon stops responding after the ceramic config gets published, and the script produces logs like:

```
(node:46403) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://6b9c2350f4a9.ngrok.io/api/v0/state/ceramic/kjzl6cwe1jw145p4zb77wfyewmtdeo8otq3mibmex6bo8d5yyges6l14cpdgpf1 reason: Unexpected token < in JSON at position 0
    at /Users/beta/codes/streams-js-tooling/apps/streams-api/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:46403) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:46403) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://6b9c2350f4a9.ngrok.io/api/v0/state/ceramic/kjzl6cwe1jw146h9rcw8dc9kck36itzllay4k5obpvge748ngi1xl5qpa0qkbtm reason: Unexpected token < in JSON at position 0
    at /Users/beta/codes/streams-js-tooling/apps/streams-api/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I'm running ceramic behind ngrok, but the same thing happens if I hit the ceramic daemon `7007` directly

**Comment by simonovic86** [comment]
Hey @Schwartz10! We've just released a new version of js-ceramic with the newest IPFS dependency. Can you try running it pls?

**Comment by simonovic86** [comment]
Hey @Schwartz10 ! Are you experiencing these errors still? We bumped the IPFS dependencies and fixed some of the issues that appeared to be causing performance issues.

**Comment by stbrody** [comment]
Hey @Schwartz10, what's the status of this issue?  Does using an external IPFS node prevent the memory leak issue from within Ceramic?

**Comment by Schwartz10** [comment]
Well, the max listeners warning occurs on the IPFS daemon when run separately, not the ceramic daemon terminal. Not sure what that indicates, probably depends on who is setting the listeners? (inside IPFS, or outside IPFS?)

**Comment by stbrody** [comment]
Right. We know there is a memory leak issue within js-ipfs, I'm trying to figure out if we have any evidence to believe that there is *also* a memory leak within ceramic itself

**Comment by stbrody** [comment]
Also, btw, it seems likely that the max listener warning is actually benign: https://github.com/ipfs/js-ipfs/issues/1060.  We're working to make the warning go away here: https://github.com/ceramicnetwork/js-ipfs-ceramic/issues/16

I'm more concerned about the potential memory leak and related performance degradation, so that's why I'm wondering if you're still seeing that happening ceramic-side since splitting ipfs out

**Comment by oed** [comment]
This should be resolved since the use of the js-DHT was removed. Can you confirm @Schwartz10?
