### ISSUE TITLE
libp2p stream reset error 

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#518]
Haven't figured out how to replicate this yet, but it seems to happen pretty frequently when running Ceramic-cli v0.13.3. It seems like it might cause the daemon to not respond to requests? Not sure yet, but wanted to put it on your radar because it will break any app that is doing simple ceramic operations.

```(node:46818) UnhandledPromiseRejectionWarning: Error: stream reset
    at Object.reset (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/stream.js:72:27)
    at Mplex._handleIncoming (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:227:16)
    at /Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:156:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Mplex.sink (/Users/jonathanschwartz/Documents/owl/streams/streams-js-tooling/apps/streams-api/node_modules/libp2p-mplex/src/mplex.js:149:9)
(Use `node --trace-warnings ...` to show where the warning was created)```

**Comment by simonovic86** [comment]
@Schwartz10 I would purpose the same separation of concerns like I described [here](https://github.com/ceramicnetwork/js-ceramic/issues/519#issuecomment-730503903). Makes sense?

**Comment by simonovic86** [comment]
This issue seems to be related to this one [111](https://github.com/libp2p/js-libp2p-mplex/issues/111).

**Comment by Schwartz10** [comment]
Yeah that issue looks very promising! 

The separation of concerns did not work - see https://github.com/ceramicnetwork/js-ceramic/issues/519#issuecomment-730609814
