### ISSUE TITLE
Local network doesn't look happy

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#632]
When running the latest ceramic-cli package (`0.16.2`) `ceramic daemon --network=local`

```
(node:51774) UnhandledPromiseRejectionWarning: Error: No usable chainId for anchoring was found.  The ceramic network 'local' supports the chains: ['eip155:1337'], but the configured anchor service 'inmemory' only supports the chains: ['inmemory:12345']
    at Function._generateNetworkOptions (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/core/lib/ceramic.js:124:19)
    at async Function.create (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/core/lib/ceramic.js:144:32)
    at async Function.create (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js:94:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51774) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:51774) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stbrody** [comment]
The `local` network expects to connect to a running instance of Ganache to perform blockchain anchoring.  You need to specify the flag `--anchorServiceApi` and point it at your locally running Ganache instance

**Comment by Schwartz10** [comment]
I see! So theoretically I should be able to use a local ceramic network and any external API that follows the anchorServiceAPI interface right? Could I also just plug in Rinkeby there if I wanted?

**Comment by stbrody** [comment]
Although Rinkeby is just a testnet, it is still a real ethereum network that is connected to other nodes, therefore it is not supported by the `local` ceramic network configuration.  The `local` configuration is designed to be completely isolated from all other nodes and only works with Ganache currently.  We do however support Rinkeby (and Ropsten) on the Ceramic network `testnet-clay`

**Comment by stbrody** [comment]
@Schwartz10, do you have any further questions on this issue, or can I go ahead and close this ticket?

**Comment by Schwartz10** [comment]
Hey @stbrody thanks for the clarification! Although I'm still a bit confused (most likely due to my superficial understanding of the relationship between ceramic network and anchor network).

A couple questions:

- What is the relationship between ceramic network and the anchoring network? 
- If ceramic network is responsible for keeping track of document HEADs, and the anchor network is responsible for "pinning" documents at specific "commits" on chain, why does the ceramic network enforce any constraints on the anchor network? 
- A small point, but ganache can also be configured to connect with other ganache nodes running on the same networkID, so not sure why (connecting to other nodes in a blockchain network) rules out rinkeby being an option for `local` ceramic config

I probably am misunderstanding something, but it seems to me like I should be able to run ceramic in `local` mode, so that my calls to resolve docs don't have to check with other ceramic nodes in the network, while also being able to "anchor" all my local docs to mainnet ethereum.

This ticket was for a bug though, so if you want to close it and reopen a new one for this anchorage <> ceramic network discuss that's fine by me!

**Comment by stbrody** [comment]
Lots of great questions here!  Sorry, this stuff is all pretty poorly documented at the moment.

Right now, there isn't really any anchoring network.  There are just individual, independent instances of ceramic-anchor-service which each can take a bunch of requests to associate a CID representing the current state of a document, and associated document's DocID, bundles them together and publishes them on chain.

The ceramic network concept exists to keep production ceramic documents and pubsub traffic isolated and separate from testing/development documents and traffic.  When you specify a ceramic network, all it does is change the libp2p pubsub topic used for messages, and change the set of blockchains that are accepted for anchoring documents published on that network.  You can see the code that controls this [here](https://github.com/ceramicnetwork/js-ceramic/blob/6a67f49c1ec407e756e65df00c73ee42bfc1ff54/packages/core/src/ceramic.ts#L173-L207).

For ceramic mainnet, it's important to enforce that all anchors happen on ethereum mainnet, otherwise the consensus and security properties of the ceramic network become compromised.  We can't allow mainnet ceramic documents to be anchored on devnets or local in-memory instance blockchains such as ganache, as doing so would discard all the security properties gained from anchoring on a blockchain in the first place.

Your case, however, is the opposite - you want disconnected ceramic nodes to anchor on the connected eth mainnet, rather than connected ceramic nodes anchoring on disconnected eth testnets.  That poses less of a direct security threat, but still could result in lots of fragmentation of the ceramic network, which isn't good for the overall health of the network.  For example, we have already had some conversations with decentralized indexing providers who plan on building an index of ceramic documents by reading our anchor records on eth mainnet.  If an anchor record on ethereum references a document that isn't accessible on the public ceramic network, that hurts the health and usability of the network.

**Comment by stbrody** [comment]
Closing due to lack of activity, feel free to reopen if your questions here have not been fully answered.
