### ISSUE TITLE
Error verifying anchor record

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#646]
Running ceramic daemon locally:

```bash
 ceramic daemon
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmXXfBc8yeS4BY2sYe7hDTwrFJnNA9JZcJf73nWFzg15z8
Swarm listening on /ip4/192.168.188.23/tcp/4002/p2p/QmXXfBc8yeS4BY2sYe7hDTwrFJnNA9JZcJf73nWFzg15z8
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmXXfBc8yeS4BY2sYe7hDTwrFJnNA9JZcJf73nWFzg15z8
Ceramic API running on port 7007
(node:143086) UnhandledPromiseRejectionWarning: Error: The anchor record couldn't be verified. Reason invalid character '/' in 'afyreif2yo4iwfw2kiefpdq7fvqrbabqftqg3227jbc5zor2zfwtklobvq/root/1/1/1/1'
    at Document._verifyAnchorRecord (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/document.js:321:19)
    at async Document._applyLogToState (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/document.js:271:17)
    at async Document._applyLog (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/document.js:242:35)
    at async /usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/document.js:154:37
    at async run (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/p-queue/dist/index.js:163:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:143086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5619)
(node:143086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:143086) UnhandledPromiseRejectionWarning: TimeoutError: request timed out
    at maybeThrowTimeoutError (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-core-utils/src/with-timeout-option.js:42:15)
    at /usr/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-core-utils/src/with-timeout-option.js:96:9
    at async Dispatcher.retrieveRecord (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/dispatcher.js:92:24)
    at async Document._fetchLog (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/document.js:169:24)
    at async /usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/document.js:152:29
    at async run (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/p-queue/dist/index.js:163:29)
(node:143086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6959)
```

The error happens after I run this and wait for the anchor service to create the anchor.
```bash
 ceramic create tile --content '{ "Ceramic": "pottery2" }'
DocID(kjzl6cwe1jw148p3qeku3sl2v30q2pgyl58cfyy91b5kc54yowv3via1gnziudm)
{
  "Ceramic": "pottery2"
}
```

Version:
```
 npm list -g @ceramicnetwork/cli
/usr/lib
└── @ceramicnetwork/cli@0.16.2
```

**Comment by oed** [comment]
@stbrody Was this one of the issues you where talking about?

**Comment by stbrody** [comment]
Talking about when?  We saw something like this when we were debugging earlier, I think when you were running the repro script, and I made some comment like "I've seen that before", is that what you're asking about?  If so, then yes, I think it was this ticket I was remembering.  I still have no idea what causes this or why it only happens sometimes.

**Comment by oed** [comment]
I just remembered that you mentioned the `The anchor record couldn't be verified` error. Ok!

**Comment by stbrody** [comment]
I can repro this reliably.  The new integration test I'm writing hits this every time.  Seems to happen any time more than one document is anchored in the same batch by the CAS.  I can also repro this manually by just creating multiple documents in quick succession.

This error is coming from IPFS, when we try to load the path through the merkle tree.  Seems like IPLD cannot properly traverse the path.  I can verify that manually loading each record in the path one at a time works, but when we pass the entire path to the dispatcher to load we get the `invalid character '/'` error.  Could this be some issue with the interplay between IPFS, IPLD, and DAG-JOSE?  I might need your help to debug this @oed, let me know if you want to look at it together at some point

**Comment by oed** [comment]
Ok, maybe we can look at it today after standup @stbrody ?
