### ISSUE TITLE
CLI pin api broken

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#716]
@oed noticed this, i'm just the notetaker

**Comment by oed** [comment]
Very simple to reproduce:
```
ceramic pin ls
(node:27523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Function.fromString (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/docid/lib/index.js:76:23)
    at Function.pinLs (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-cli-utils.js:191:36)
    at Command.<anonymous> (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js:111:47)
    at Command.listener [as _actionHandler] (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:970:12)
    at Command._dispatchSubcommand (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:970:12)
    at Command.parse (/Users/oed/.nvm/versions/node/v14.11.0/lib/node_modules/@ceramicnetwork/cli/node_modules/commander/index.js:801:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:27523) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stbrody** [comment]
https://github.com/ceramicnetwork/js-ceramic/issues/579 would likely have caught this.

**Comment by stbrody** [comment]
It's actually not just `cli ls` that's broken. cli `pin add` and `pin rm` are broken too
