### ISSUE TITLE
Pubsub subscribe timeout failing

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#737]
When adding a timeout to the `ipfs.pubsub.subscribe` call like below

```js
await this._ipfs.pubsub.subscribe(
  this.topic,
  this.handleMessage.bind(this),
  {timeout: IPFS_GET_TIMEOUT} // timeout is causing tests to fail
)
```

### core/../ceramic-anchor-tests.ts

If I include the timeout __*without*__ mocking `ipfs.pubsub.subscribe` I get these errors and some failed tests.

```
// these errors are coming from `subscribe` not being mocked
  console.error
    TypeError: Cannot read property 'Symbol(Symbol.asyncIterator)' of undefined
        at Object.subscribe (/js-ceramic/node_modules/ipfs-core/node_modules/ipfs-core-utils/src/with-timeout-option.js:56:14)
        at Dispatcher._subscribe (/js-ceramic/packages/core/src/dispatcher.ts:76:33)
        at Dispatcher.init (/js-ceramic/packages/core/src/dispatcher.ts:64:16)
        at Function.create (/js-ceramic/packages/core/src/ceramic.ts:256:5)
        at createCeramic (/js-ceramic/packages/core/src/__tests__/ceramic-anchor.test.ts:47:19)
        at async Promise.all (index 1)
        at Object.<anonymous> (/js-ceramic/packages/core/src/__tests__/ceramic-anchor.test.ts:136:34)
```

If I add mocking for `ipfs.pubsub.subscribe` all tests fail.

**Comment by valmack** [comment]
I think the issue is if we are running and IPFS node in process there should be no timeout option

**Comment by valmack** [comment]
This only occurs when running IPFS in process so it seems to be a bug in IPFS core.

**Comment by valmack** [comment]
Created issue in ipfs repo so closing this one https://github.com/ipfs/js-ipfs/issues/3472
