### ISSUE TITLE
More requests timing out

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#798]
I'm not sure if this is known, but we are still seeing request timeout errors in the ceramic daemon after running a script:

Error:
```
(node:1667) UnhandledPromiseRejectionWarning: TimeoutError: Request timed out
    at Timeout.<anonymous> (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/ipfs-utils/src/http.js:28:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)
(node:1667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Script:
```js
import fs from "fs";
import Ceramic from "@ceramicnetwork/http-client";
import IdentityWallet from "3id-did-provider";
import {
  createDefinition,
  publishIDXConfig,
  publishSchema,
} from "@ceramicstudio/idx-tools";
import { Aliases } from "@ceramicstudio/idx";
import { fullSchemaList } from "@daemon-land/types";
import getBasicAuth from "../src/utils/getBasicAuth";

const auth = getBasicAuth("squad@infinitescroll.org");

const publishSchemas = async (
  ceramic: Ceramic
): Promise<
  Record<string, { name: string; docID: string; version: string }>
> => {
  const schemas = await Promise.all(
    fullSchemaList.map(async (schema) => {
      const doc = await publishSchema(ceramic, schema);
      return {
        name: schema.name,
        docID: doc.id.toUrl(),
        version: doc.commitId.toUrl(),
      };
    })
  );
  const schemaMap = {} as {
    [key: string]: { name: string; docID: string; version: string };
  };
  schemas.forEach((s) => {
    schemaMap[s.name] = s;
  });

  return schemaMap;
};

const publishDefinitions = async (
  ceramic: Ceramic,
  schemas: Record<string, { name: string; docID: string; version: string }>
): Promise<Aliases> => {
  const definitions = {} as Aliases;
  for (const k in schemas) {
    const doc = await createDefinition(ceramic, {
      name: k,
      schema: schemas[k].version,
      description: "STUBBED DESCRIPTION",
    });
    definitions[k] = doc.id.toString();
  }
  return definitions;
};

const seedAliases = async () => {
  const ceramic = new Ceramic();
  const idWallet = await IdentityWallet.create({
    authId: auth.ID,
    authSecret: auth.secret,
    getPermission: () => Promise.resolve([]),
    ceramic,
  });
  await ceramic.setDIDProvider(idWallet.getDidProvider());
  console.log("SET THE DID PROVIDER. ID WALLETS DID: ", idWallet.id);
  const config = await publishIDXConfig(ceramic);
  console.log("Published IDX config");
  const schemas = await publishSchemas(ceramic);
  console.log("Published schemas", schemas);
  const definitions = await publishDefinitions(ceramic, schemas);
  fs.writeFile(
    `${__dirname}/../aliases.json`,
    JSON.stringify({ ...definitions, ...config.definitions }),
    console.error
  );

  await ceramic.close();
};

seedAliases();
```

Note - I'm not actually sure this is something that's breaking things for us... will know more in the coming days.

**Comment by valmack** [comment]
Yes we are seeing the same thing. Taking a deeper dive into it now. Thanks for reporting and for sure keep us posted

**Comment by ukstv** [comment]
With the latest Fri/Sat changes, the script runs just all right.
