### ISSUE TITLE
'Unexpected token ] in JSON at position 303'

### ISSUE THREAD

**Issue by pvanroos** [ceramicnetwork/js-ceramic#818]
I just upgrade from 0.19.0 to 0.20.0 using 'npm install'.  Ran 'ceramic daemon' after successful install.  See output below:

Installed on:  Ubuntu 18.04x64

JSON has a trailing comma from this URL:

https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/testnet-clay.json

ceramicuser@CeramicNode-1:~$ ceramic daemon
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmXvD8TJ5Fbn9vfwPeWf3LYDBLprGbZyTJPrMcNmB5egQr
...

Connecting to peers found in 'https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/testnet-clay.json'
(node:11153) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/testnet-clay.json reason: Unexpected token ] in JSON at position 303
    at /usr/lib/node_modules/@ceramicnetwork/cli/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchJson (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/peer-discovery.js:14:17)
    at async connectToPeers (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/peer-discovery.js:27:19)
    at async Object.periodicallyConnectToPeers (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/peer-discovery.js:41:5)
    at async Function.create (/usr/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core/lib/ceramic.js:180:13)
    at async Function.create (/usr/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js:97:25)
    at async Command.<anonymous> (/usr/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js:28:5)
(node:11153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michaelsena** [comment]
Thanks for bringing this to our attention @pvanroos! @oed and @stbrody seems the json was incorrectly formatted. I think Paul already submitted a PR fixing it.

**Comment by oed** [comment]
Thanks for reporting @pvanroos removed the trailing comma, so this should be fixed now!

**Comment by pvanroos** [comment]
No worries.  Easy fix.  I wish all my bugs were like that.  :-)
